In [18]:
import numpy as np
import matplotlib.pyplot as plt
from importlib import reload
from pymeasure.instruments import srs

In [86]:
reload(srs)
lockin1 = srs.SR830('GPIB2::9::INSTR')
print(lockin1.id)
print(lockin1.x, lockin1.y)

lockin1.sample_frequency = 128
print(lockin1.sample_frequency)

Stanford_Research_Systems,SR830,s/n86942,ver1.07
5.1941e-12 -3.34028e-11
128


In [87]:
# lockin1.buffer_measure_from_bytes(1280, fast=True)
lockin1.buffer_measure(1280)

(5.967022687590473e-12,
 6.574860334990328e-13,
 -3.238161960794628e-11,
 7.222063796495525e-13)

In [81]:
lockin1.buffer_measure_from_bytes(1280, fast=True)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)

In [58]:

currentCount = lockin1.buffer_count
print(currentCount)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xa6 in position 2: ordinal not in range(128)

In [59]:
currentCount = lockin1.buffer_count
print(currentCount)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xfa in position 0: ordinal not in range(128)

In [52]:
lockin1.buffer_count

3929

In [ ]:
lockin1.fill_buffer(1280)

(array([5.1869897e-12, 5.2083060e-12, 5.2296223e-12, ..., 5.5564719e-12,
        5.5635774e-12, 5.5706828e-12], dtype=float32),
 array([-3.2415182e-11, -3.2415182e-11, -3.2408076e-11, ...,
        -3.2791769e-11, -3.2813086e-11, -3.2834402e-11], dtype=float32))

UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 3: ordinal not in range(128)

In [8]:
lockin1.pause_buffer()

In [9]:
lockin1.buffer_count

5891

In [12]:
print(lockin1.get_buffer(1))
print(lockin1.get_buffer(2))

[5.7341076e-12 5.7625293e-12 5.7838456e-12 ... 4.4338144e-12 4.4622361e-12
 4.4906578e-12]
[-3.1647795e-11 -3.1647795e-11 -3.1640690e-11 ... -3.2386760e-11
 -3.2379655e-11 -3.2358338e-11]


In [13]:
lockin1.read_buffer_bytes()

(array([5.73407988e-12, 5.76250159e-12, 5.78381787e-12, ...,
        4.43378667e-12, 4.46220838e-12, 4.49063009e-12]),
 array([-3.16475735e-11, -3.16475735e-11, -3.16404680e-11, ...,
        -3.23865379e-11, -3.23794325e-11, -3.23581162e-11]))

In [15]:
lockin1.write('FAST0')

In [14]:
print(lockin1.id)
lockin1.reset_buffer()
lockin1.start_buffer(False)
lockin1.wait_for_buffer(512)

Stanford_Research_Systems,SR830,s/n86942,ver1.07


KeyboardInterrupt: 

In [20]:
lockin1.buffer_measure_from_bytes(1280)

KeyboardInterrupt: 